### ISSUE TITLE
@ContributesGraphExtension "asContribution" type ChildGraph.Factory is not merged supertype of "ParentGraph"

### ISSUE THREAD

**Issue by jmalpasuto** [ZacSweers/metro#824]
### Description

Given a `ParentGraph`
```kotlin
@SingleIn(ParentScope::class)
@DependencyGraph(ParentScope::class, isExtendable = true)
interface ParentGraph {
}
```

and a `ChildGraph` extension
```kotlin
@SingleIn(ChildScope::class)
@ContributesGraphExtension(ChildScope::class, isExtendable = true)
interface ChildGraph {

  /** Factory for creating the child graph. */
  @ContributesGraphExtension.Factory(ParentScope::class)
  interface Factory {
    /** Create a child graph with the parent graph as a dependency. */
    fun create(): ChildGraph
  }
}
```

This line fails
```kotlin
val childGraph = parentGraph.asContribution<ChildGraph.Factory>().create()
```
with

```
e: file:///Users/*/*/Main.kt:17:47 `asContribution` type argument 'dev.zacsweers.metro.sample.multimodule.child.ChildGraph.Factory' is not a merged supertype of dev.zacsweers.metro.sample.multimodule.parent.ParentGraph.
```

### Self-contained Reproducer

https://github.com/jmalpasuto/metro/pull/2/commits/9c4ee2b29fa858eb918137c86048ad8f1fe629c0

I _think_ this might be an issue with multi module projects. It looks like you have tests for this in a single module that pass

### Metro version

0.5.2

### Context

Using `samples/multi-module-test`

**Comment by ZacSweers** [comment]
This is fixed on main 👍

**Comment by jmalpasuto** [comment]
I just rebased against main and it's still happening :( (updated the description)

`main@`https://github.com/ZacSweers/metro/commit/a116e3228bed1505b3d839d87d6f1f4f49ff0d8a

**Comment by ZacSweers** [comment]
Both of these tests pass for me (#831)

// Single module
```kotlin
// https://github.com/ZacSweers/metro/issues/824
abstract class ParentScope
abstract class ChildScope

@SingleIn(ParentScope::class)
@DependencyGraph(ParentScope::class, isExtendable = true)
interface ParentGraph {
}

@SingleIn(ChildScope::class)
@ContributesGraphExtension(ChildScope::class, isExtendable = true)
interface ChildGraph {

  /** Factory for creating the child graph. */
  @ContributesGraphExtension.Factory(ParentScope::class)
  interface Factory {
    /** Create a child graph with the parent graph as a dependency. */
    fun create(): ChildGraph
  }
}

fun box(): String {
  val parentGraph = createGraph<ParentGraph>()
  val childGraph = parentGraph.asContribution<ChildGraph.Factory>().create()
  return "OK"
}
```

// Multi module
```kotlin
// https://github.com/ZacSweers/metro/issues/824
// MODULE: lib
abstract class ParentScope
abstract class ChildScope

@SingleIn(ChildScope::class)
@ContributesGraphExtension(ChildScope::class, isExtendable = true)
interface ChildGraph {

  /** Factory for creating the child graph. */
  @ContributesGraphExtension.Factory(ParentScope::class)
  interface Factory {
    /** Create a child graph with the parent graph as a dependency. */
    fun create(): ChildGraph
  }
}

// MODULE: main(lib)
@SingleIn(ParentScope::class)
@DependencyGraph(ParentScope::class, isExtendable = true)
interface ParentGraph {
}

fun box(): String {
  val parentGraph = createGraph<ParentGraph>()
  val childGraph = parentGraph.asContribution<ChildGraph.Factory>().create()
  return "OK"
}
```

The issue with your repro is that `ParentGraph` _does not_ have a view of `ChildGraph` in its dependencies. You have actually tried to switch its dependency ordering there (the `child-graph` module depends on the parent.)

**Comment by jmalpasuto** [comment]
Ahhhh, my bad. Thanks for digging into it!
